[package]
name = "boiling_frog_dbus"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
once_cell = "1.17.1"
zbus = "3.11.0"
tokio = {version = "1.26.0", features = ["macros", "rt-multi-thread"] }

[lib]
name = "boiling_frog_dbus"
