[package]
name = "boiling_frog"
version.workspace = true
edition = "2021"

[dependencies]
glib = "0.20.7"
gtk = { version = "0.9.5", package = "gtk4" }
boiling_frog_dbus = { path = "../boiling_frog_dbus" }
