[package]
name = "boiling_frog"
version = "0.1.0"
edition = "2021"

[dependencies]
glib = "0.17.2"
gtk = { version = "0.6.2", package = "gtk4" }
boiling_frog_dbus = { path = "../boiling_frog_dbus" }
tokio = {version = "1.26.0", features = ["macros", "rt-multi-thread"] }
