[package]
name = "boiling_frog"
version.workspace = true
edition = "2021"

[dependencies]
glib = "0.17.2"
gtk = { version = "0.6.2", package = "gtk4" }
boiling_frog_dbus = { path = "../boiling_frog_dbus" }
